version: "3.8"

networks:
  s0rago-net:
    driver: bridge
    name: s0rago-net

services:
  
  image-resizer:
    container_name: image-resizer
    image: 'resizer:latest'
    build:
      context: ./image-resizer
    networks:
      s0rago-net:
        aliases:
          - image-resizer
    environment:
      SERVICE_NAME: afonin.image-resizer
      PORT: 5000
      HOST: 0.0.0.0
      ENCODING: UTF-8
      BASE_API: /afonin/api/v1/image
    ports:
      - 6969:5000
    expose:
      - 6969
      