apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment-producer-afonin
spec:
  selector:
    matchLabels:
      app: kafka-producer-afonin
  template:
    metadata:
      labels:
        app: kafka-producer-afonin
    spec:
      containers:
      - name: kafka-producer-afonin
        image: s0rago/data-management:producer
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE_NAME
            value: afonin.producer
          - name: SERVER
            # value: 51.250.30.101:9092
            value: kafka-service:9092 
          - name: TOPIC
            value: logs-topic
          - name: PORT
            value: "5000"
          - name: HOST
            value: 0.0.0.0
          - name: ENCODING
            value: UTF-8          
