apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-prod-deployment-afonin
spec:
  selector:
    matchLabels:
      app: kafka-prod-afonin
  template:
    metadata:
      labels:
        app: kafka-prod-afonin
    spec:
      containers:
      - name: kafka-prod-afonin
        image: s0rago/data-management:producer
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
        env:
          - name: service_name
            value: afonin.prod
          - name: server
            # value: 51.250.30.101:9092
            value: kafka-service:9092 
          - name: topic
            value: logs-topic
          - name: port
            value: "5000"
          - name: host
            value: 0.0.0.0
