apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-image-afonin # Менять
spec:
  selector:
    matchLabels:
      app: image-afonin # Менять
  template:
    metadata:
      labels:
        app: image-afonin # Менять
    spec:
      containers:
      - name: image-afonin # Менять
        image: s0rago/data-management:image-resizer # Менять
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000 
        env: # Менять ниже на свои, которые в коде юзатся
          - name: SERVICE_NAME
            value: afonin.image-resizer
          - name: PORT
            value: "5000"
          - name: HOST
            value: 0.0.0.0
          - name: ENCODING
            value: UTF-8
          - name: BASE_API
            value: /afonin/api/v1/image
